about :

  name : 'local.import'
  description : 'To use local modules'
  version : 0.0.1

submodule :

  PathFundamentals : git+https:///github.com/Wandalen/wPathFundamentals.git/out/wPathFundamentals#master
  localOne : ./modules/localOne/
  localTwo : ./modules/localTwo/out/local