about :

  name : 'local.import'
  description : 'To use local modules'
  version : 0.0.1

submodule :

  PathBasic : git+https:///github.com/Wandalen/wPathBasic.git/out/wPathBasic#master
  localOne : ./modules/localOne/
  localTwo : ./modules/localTwo/out/local