
path :

  source : git+https:///github.com/Wandalen/wPathFundamentals.git
  pathFundamentals : 'wPathFundamentals'

reflector :

  download1 :
    filePath :
      path::source : path::pathFundamentals

  download2 :
    src :
      filePath :
        path::source : path::pathFundamentals

  download3 :
    dst :
      filePath :
        path::source : path::pathFundamentals

  download4 :
    src :
      prefixPath : path::source
      filePath :
        path::source : path::pathFundamentals

  download5 :
    src :
      prefixPath : path::source
    filePath :
      path::source : path::pathFundamentals

  download6 :
    src :
      prefixPath : path::source
    dst :
      basePath : .
      prefixPath : path::pathFundamentals

step :

  download1 :
    inherit : predefined.reflect
    reflector :
      reflector::download1

  download2 :
    inherit : predefined.reflect
    reflector :
      reflector::download2

build :

  download1 :
    steps :
      - step::download1

  download2 :
    steps :
      - step::download2
