
about :
  name : 'Download'
  version : '0.0.0'

submodule :

  Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#master

path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug :
    path : './out.debug'

reflector :

  reflect.proto :
    inherit : predefined.*
    filePath :
      path::proto : path::out.*=1

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exportedFiles*=1
    dstFilter :
      basePath : .
      prefixPath : path::out.debug

step :

  delete.out.debug :
    inherit : predefined.delete
    filePath : path::out.debug
    criterion :
      debug : 1

  reflect.proto :
    inherit : predefined.reflect
    reflector :
      reflector::reflect.proto*=1

  reflect.submodules :
    inherit : predefined.reflect
    reflector :
      reflector::reflect.submodules*=1

  export.proto :
    inherit : export
    export : path::proto
    tar : 0

build :

  debug.raw :
    criterion :
      default : 1
    steps :
      - delete.out.debug
      - submodules.download
      - step::reflect.proto
      - step::reflect.submodules

  export :
    criterion :
      default : 1
      export : 1
    steps :
      - build::debug.raw
      - step::export.proto
