
path :

  google : http:///www.google.com
  local : File.html

step :

  view1 :
    inherit : predefined.view
    filePath : path::google

  view2 :
    inherit : predefined.view
    filePath : path::local

build :

  view1 :
    steps :
      - step::view1

  view2 :
    steps :
      - step::view2
