about :

  name : deleteOut
  description : "To test named will-files"

path :

  fileToDelete :
    path : 'out'

step  :

  delete.submodule :
    inherit : files.delete
    filePath : path::fileToDelete


build :

  delete.submodule :
    criterion :
      default : 1
    steps :
      - delete.*