about :

  name : selectorWithGlob
  description : "Using selector with glob to choise path"
  version : 0.0.1

path :

  in : '.'
  out : 'out'
  fileToExport.debug :
    criterion :
      debug : 1
    path : 'fileDebug.txt'

  fileToExport.release :
    criterion :
      debug : 0
    path : 'fileRelease.txt'

step  :
  export.debug :
    inherit : module.export
    export : path::fileToExport.*
    tar : 0
    criterion :
      debug : 1

  export.release :
    inherit : module.export
    export : path::fileToExport.*
    tar : 0
    criterion :
      debug : 0

build :

  export.debug :
    criterion :
      export : 1
      debug : 1
    steps :
      - export.*

  export.release :
    criterion :
      export : 1
      debug : 0
    steps :
      - export.*
