about :

  name : usingJS
  description : "To use JS in willbe"
  version : 0.0.1

path :

  js.path :
    path : 'server.js'

step  :

  run.js :
      js : path::js.path
  run.server :
      shell : node ser*

build :

  run.js :
      criterion :
          default : 1
      steps :
          - run.js

  run.server :
      steps :
          - run.server