about :

    name : predefinedSteps
    description : "To use predefined submodule control steps"
    version : 0.0.1

submodule :

    ModuleForTesting1 : git+hd://../_repo/ModuleForTesting1?out=out/wModuleForTesting1.out.will@master
    ModuleForTesting2 : git+hd://../_repo/ModuleForTesting2?out=out/wModuleForTesting2.out.will@master
    # Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools.out.will@master
    # PathBasic : git+https:///github.com/Wandalen/wPathBasic.git/out/wPathBasic.out.will@master

step :

    echo :
        shell: echo "Done"

build :

    download :
        steps :
           - submodules.download

    upgrade :
        steps :
           - submodules.update

    clean :
        steps :
           - submodules.clean

    build :
        criterion :
          default : 1
        steps :
           - submodules.clean
           - submodules.download
           - echo
