submodule :
  ModuleForTesting1 : npm:///wmodulefortesting1
  ModuleForTesting2 : npm:///wmodulefortesting2@alpha
  ModuleForTesting2b : npm:///wmodulefortesting2b#0.0.30
  # Path : npm:///wpathbasic@alpha
  # Uri : npm:///wuribasic#0.6.131


about :

  name : supermodule
  version : 0.1.0

path :

  in : .
  out : out

build :

  debug :
    criterion :
      default : 1
      debug : 1
    steps :
      - step::submodules.download
