
about :

  name : "willbe"
  description : "Utility to manage modules of complex modular systems"
  version : "0.3.166"
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

execution :

  scripts :
    test : wtest proto
    docgen : wdocgen staging

path :

  repository : git+https://github.com/Wandalen/willbe.git
  bugs : https://github.com/Wandalen/willbe/issues

step :

  export.proto :
    inherit : predefined.export
    export : path::proto
    tar : 0
    criterion :
      debug : 1
      proto : 1
      doc : 0

  export.doc :
    inherit : predefined.export
    export : path::doc
    tar : 0
    criterion :
      debug : 1
      doc : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      raw : 1
      proto : 1
      doc : 0
      export : 1
      tar : 1
      public : 1
    steps :
      - build::debug.raw
      - step::export.proto

  doc.export :
    criterion :
      export : 1
      debug : 1
      doc : 1
    steps :
      - step::export.doc
