
submodule :

  willbe : git+https:///github.com/volodymyrmigdal/willbe.git/out/willbe#master

step :

  list.dir :
    currentPath : .
    shell : ls

build :

  debug :
    criterion :
      debug : 1
      default : 1
    steps :
      - step::list.dir*=1


