
submodule :

  submodule : submodule

path :

  in : '.'
  out : './out'
  out.debug : './out/debug'
  module.dir : './module'

reflector :

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exportedFiles*=1
    dst :
      basePath : .
      prefixPath : "{path::out.*=1}"
    criterion :
      debug : [ 0,1 ]
      
step :
    
  submodules.informal.export :
    currentPath : path::module.dir
    shell : 'node {path::will} .each module .export'

build :
  
  variant1 :
    criterion :
      default : 1
      debug : 1
    steps :
      - step::reflect.submodules.*=1

  variant2 :
    criterion :
      debug : 1
    steps :
      - step::submodules.informal.export
      - step::submodules.reload
      - step::reflect.submodules.*=1
