
about :

  name : many
  version : 0.1.0

step :

  export.out.debug :
    inherit : module.export
    export : path::out.debug
    tar : 0
    criterion :
      debug : 1
      content: proto

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      export : 1
      content: proto
    steps :
      - build::debug.raw
      - step::export.out.debug
