
submodule :

  Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#master
  Logger : git+https:///github.com/Wandalen/wLogger.git/out/wLogger#master
  LoggerToJs : git+https:///github.com/Wandalen/wLoggerToJs.git/out/wLoggerToJs#master
  Consequence : git+https:///github.com/Wandalen/wConsequence.git/out/wConsequence#master
  Instancing : git+https:///github.com/Wandalen/wInstancing.git/out/wInstancing#master
  EventHandler : git+https:///github.com/Wandalen/wEventHandler.git/out/wEventHandler#master
  Copyable : git+https:///github.com/Wandalen/wCopyable.git/out/wCopyable#master
  FieldsStack : git+https:///github.com/Wandalen/wFieldsStack.git/out/wFieldsStack#master
  Looker : git+https:///github.com/Wandalen/wLooker.git/out/wLooker#master
  PathFundamentals : git+https:///github.com/Wandalen/wPathFundamentals.git/out/wPathFundamentals#master
  Proto : git+https:///github.com/Wandalen/wProto.git/out/wProto#master
  Selector : git+https:///github.com/Wandalen/wSelector.git/out/wSelector#master
  SelectorExtra : git+https:///github.com/Wandalen/wSelectorExtra.git/out/wSelectorExtra#master

  Stringer : git+https:///github.com/Wandalen/wStringer.git/out/wStringer#master
  ArraySorted : git+https:///github.com/Wandalen/wArraySorted.git/out/wArraySorted#master
  ArraySparse : git+https:///github.com/Wandalen/wArraySparse.git/out/wArraySparse#master
  ProcessBasic : git+https:///github.com/Wandalen/wProcessBasic.git/out/wProcessBasic#master
  UriFundamentals : git+https:///github.com/Wandalen/wUriFundamentals.git/out/wUriFundamentals#master

  LookerExtra : git+https:///github.com/Wandalen/wLookerExtra.git/out/wLookerExtra#master
  Traverser : git+https:///github.com/Wandalen/wTraverser.git/out/wTraverser#master
  WebUriFundamentals : git+https:///github.com/Wandalen/wWebUriFundamentals.git/out/wWebUriFundamentals#master
  Cloner : git+https:///github.com/Wandalen/wCloner.git/out/wCloner#master
  StringsExtra : git+https:///github.com/Wandalen/wStringsExtra.git/out/wStringsExtra#master
  Procedure : git+https:///github.com/Wandalen/wProcedure.git/out/wProcedure#master

  Gdf : git+https:///github.com/Wandalen/wGdfStrategy.git/out/wGdfStrategy#master
  Replicator : git+https:///github.com/Wandalen/wReplicator.git/out/wReplicator#master
  RoutineFundamentals : git+https:///github.com/Wandalen/wRoutineFundamentals.git/out/wRoutineFundamentals#master
  EntityFundamentals : git+https:///github.com/Wandalen/wEntityFundamentals.git/out/wEntityFundamentals#master

  # --

  RegexpObject : git+https:///github.com/Wandalen/wRegexpObject.git/out/wRegexpObject#master
  Color : git+https:///github.com/Wandalen/wColor.git/out/wColor#master
  Color256 : git+https:///github.com/Wandalen/wColor256.git/out/wColor256#master
  ChangeTransactor : git+https:///github.com/Wandalen/wChangeTransactor.git/out/wChangeTransactor#master
  Vocabulary : git+https:///github.com/Wandalen/wVocabulary.git/out/wVocabulary#master
  CommandsAggregator : git+https:///github.com/Wandalen/wCommandsAggregator.git/out/wCommandsAggregator#master
  CommandsConfig : git+https:///github.com/Wandalen/wCommandsConfig.git/out/wCommandsConfig#master
  Files : git+https:///github.com/Wandalen/wFiles.git/out/wFiles#master
  FilesArchive : git+https:///github.com/Wandalen/wFilesArchive.git/out/wFilesArchive#master
  Verbal : git+https:///github.com/Wandalen/wVerbal.git/out/wVerbal#master
  StateStorage : git+https:///github.com/Wandalen/wStateStorage.git/out/wStateStorage#master
  StateSession : git+https:///github.com/Wandalen/wStateSession.git/out/wStateSession#master
  PathTranslator : git+https:///github.com/Wandalen/wPathTranslator.git/out/wPathTranslator#master
  TranspilationStrategy : git+https:///github.com/Wandalen/wTranspilationStrategy.git/out/wTranspilationStrategy#master
  NameMapper : git+https:///github.com/Wandalen/wNameMapper.git/out/wNameMapper#master
  TemplateTreeResolver : git+https:///github.com/Wandalen/wTemplateTreeResolver.git/out/wTemplateTreeResolver#master
  TemplateTreeEnvironment : git+https:///github.com/Wandalen/wTemplateTreeEnvironment.git/out/wTemplateTreeEnvironment#master
  TemplateFileWriter : git+https:///github.com/Wandalen/wTemplateFileWriter.git/out/wTemplateFileWriter#master

  MathScalar : git+https:///github.com/Wandalen/wMathScalar.git/out/wMathScalar#master
  MathVector : git+https:///github.com/Wandalen/wMathVector.git/out/wMathVector#master
  MathSpace : git+https:///github.com/Wandalen/wMathSpace.git/out/wMathSpace#master
  MathConcepts : git+https:///github.com/Wandalen/wMathConcepts.git/out/wMathConcepts#master

path :

  proto : './proto'
  temp : 'out'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
    criterion :
      debug : 1

reflector :

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst :
      prefixPath : "{path::out.*=1}"
    criterion :
      content: proto

step :

  clean.out :
    inherit : files.delete
    filePath : path::out.*=1
    criterion :
      debug : [ 0,1 ]

build :

  debug.raw :
    criterion :
      default : 1
      debug : 1
      raw : 1
      content: proto
    steps :
      - submodules.download
      - clean.out.*=1
      - reflect.submodules*=1
