
submodule :

  ModuleForTesting1 : git+https:///github.com/Wandalen/wModuleForTesting1.git/!master
  Logger : git+https:///github.com/Wandalen/wLogger.git/!master
  LoggerToJs : git+https:///github.com/Wandalen/wLoggerToJs.git/!master
  Consequence : git+https:///github.com/Wandalen/wConsequence.git/!master
  Instancing : git+https:///github.com/Wandalen/wInstancing.git/!master
  EventHandler : git+https:///github.com/Wandalen/wEventHandler.git/!master
  Copyable : git+https:///github.com/Wandalen/wCopyable.git/!master
  FieldsStack : git+https:///github.com/Wandalen/wFieldsStack.git/!master
  Looker : git+https:///github.com/Wandalen/wLooker.git/!master
  PathFundamentals : git+https:///github.com/Wandalen/wPathFundamentals.git/!master
  ModuleForTesting12 : git+https:///github.com/Wandalen/wModuleForTesting12.git/!master
  Selector : git+https:///github.com/Wandalen/wSelector.git/!master
  SelectorExtra : git+https:///github.com/Wandalen/wSelectorExtra.git/!master

  Stringer : git+https:///github.com/Wandalen/wStringer.git/!master
  ArraySorted : git+https:///github.com/Wandalen/wArraySorted.git/!master
  ArraySparse : git+https:///github.com/Wandalen/wArraySparse.git/!master
  ProcessBasic : git+https:///github.com/Wandalen/wProcessBasic.git/!master
  UriFundamentals : git+https:///github.com/Wandalen/wUriFundamentals.git/!master

  LookerExtra : git+https:///github.com/Wandalen/wLookerExtra.git/!master
  Traverser : git+https:///github.com/Wandalen/wTraverser.git/!master
  WebUriFundamentals : git+https:///github.com/Wandalen/wWebUriFundamentals.git/!master
  Cloner : git+https:///github.com/Wandalen/wCloner.git/!master
  StringsExtra : git+https:///github.com/Wandalen/wStringsExtra.git/!master
  ModuleForTesting12ab : git+https:///github.com/Wandalen/wModuleForTesting12ab.git/!master

  Gdf : git+https:///github.com/Wandalen/wGdf.git/!master
  Replicator : git+https:///github.com/Wandalen/wReplicator.git/!master
  RoutineFundamentals : git+https:///github.com/Wandalen/wRoutineFundamentals.git/!master
  EntityFundamentals : git+https:///github.com/Wandalen/wEntityFundamentals.git/!master

  # --

  RegexpObject : git+https:///github.com/Wandalen/wRegexpObject.git/!master
  ModuleForTesting1a : git+https:///github.com/Wandalen/wModuleForTesting1a.git/!master
  ModuleForTesting1a256 : git+https:///github.com/Wandalen/wModuleForTesting1a256.git/!master
  ChangeTransactor : git+https:///github.com/Wandalen/wChangeTransactor.git/!master
  Vocabulary : git+https:///github.com/Wandalen/wVocabulary.git/!master
  CommandsAggregator : git+https:///github.com/Wandalen/wCommandsAggregator.git/!master
  CommandsConfig : git+https:///github.com/Wandalen/wCommandsConfig.git/!master
  Files : git+https:///github.com/Wandalen/wFiles.git/!master
  FilesArchive : git+https:///github.com/Wandalen/wFilesArchive.git/!master
  Verbal : git+https:///github.com/Wandalen/wVerbal.git/!master
  StateStorage : git+https:///github.com/Wandalen/wStateStorage.git/!master
  StateSession : git+https:///github.com/Wandalen/wStateSession.git/!master
  PathTranslator : git+https:///github.com/Wandalen/wPathTranslator.git/!master
  TranspilationStrategy : git+https:///github.com/Wandalen/wTranspile.git/!master
  NameMapper : git+https:///github.com/Wandalen/wNameMapper.git/!master
  TemplateTreeResolver : git+https:///github.com/Wandalen/wTemplateTreeResolver.git/!master
  TemplateTreeEnvironment : git+https:///github.com/Wandalen/wTemplateTreeEnvironment.git/!master
  TemplateFileWriter : git+https:///github.com/Wandalen/wTemplateFileWriter.git/!master

  MathScalar : git+https:///github.com/Wandalen/wMathScalar.git/!master
  MathVector : git+https:///github.com/Wandalen/wMathVector.git/!master
  MathMatrix : git+https:///github.com/Wandalen/wMathMatrix.git/!master
  MathModels : git+https:///github.com/Wandalen/wMathModels.git/!master

path :

  proto : './proto'
  temp : 'out'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
    criterion :
      debug : 1

reflector :

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst :
      prefixPath : "{path::out.*=1}"
    criterion :
      content: proto

step :

  clean.out :
    inherit : files.delete
    filePath : path::out.*=1
    criterion :
      debug : [ 0,1 ]

build :

  debug.raw :
    criterion :
      default : 1
      debug : 1
      raw : 1
      content: proto
    steps :
      - submodules.download
      - clean.out.*=1
      - reflect.submodules*=1
