
about :

  name : single
  description : "Single file module"
  version : 0.0.1

path :

  in : '.'
  out : '.'
  export : './Single.js'

step  :
  export.single :
    inherit : export
    tar : 0
    export : path::export

build :

  export :
      criterion :
        default : 1
        export : 1
      steps :
        - export.single