
submodule :

path :

  proto : './proto'
  temp : 'out'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
    criterion :
      debug : 'debug'
      compiled : 'raw'
      tests : 'no.tests'
  out.compiled.debug :
    path : './out/compiled.debug'
    criterion :
      debug : 'debug'
      compiled : 'compiled'
      tests : 'no.tests'
  out.raw.release :
    path : './out/raw.release'
    criterion :
      debug : 'release'
      compiled : 'raw'
      tests : 'no.tests'
  out.release :
    path : './out/release'
    criterion :
      debug : 'release'
      compiled : 'compiled'
      tests : 'no.tests'
  out.tests.compiled.debug :
    path : './out/tests.compiled.debug'
    criterion :
      debug : 'debug'
      compiled : 'compiled'
      tests : 'only.tests'
  out.tests.compiled.release :
    path : './out/tests.compiled.release'
    criterion :
      debug : 'release'
      compiled : 'compiled'
      tests : 'only.tests'

reflector :

  reflect.proto :
    inherit : predefined.*
    criterion :
      debug : [ 'debug', 'release' ]
      compiled : 'raw'
    filePath :
      path::proto : path::out.*=1

  transpile.proto.raw.no.tests :
    inherit : predefined.*
    criterion :
      tests : 'no.tests'
      compiled : 'raw'
      debug : [ 'debug', 'release' ]
    filePath :
      '**.test*' : 0
      '**.test/**' : 0
      path::proto : '{path::out.*=1}'

  transpile.proto.compiled.no.tests :
    inherit : predefined.*
    criterion :
      tests : 'no.tests'
      compiled : 'compiled'
      debug : [ 'debug', 'release' ]
    filePath :
      '**.test*' : 0
      '**.test/**' : 0
      path::proto : '{path::out.*=1}/Main.s'

  transpile.proto.compiled.only.tests :
    inherit : predefined.*
    criterion :
      tests : 'only.tests'
      compiled : 'compiled'
      debug : [ 'debug', 'release' ]
    filePath :
      '**.test*' : 1
      path::proto : '{path::out.*=1}/Tests.s'

step :

  reflect.proto :
    inherit : predefined.reflect
    reflector : reflector::reflect.proto..compiled.*=1
    criterion :
      debug : [ 'debug', 'release' ]
      raw : [ 'raw', 'compiled' ]

  transpile.proto :
    inherit : predefined.transpile
    reflector : reflector::transpile.proto.compiled.*=1
    criterion :
      tests : [ 'no.tests', 'only.tests' ]
      debug : [ 'debug', 'release' ]
      raw : 'compiled'

build :

  debug.raw :
    criterion :
      default : 1
      debug : 'debug'
      raw : 1
    steps :
      - reflect.proto.*=1

  debug.compiled :
    criterion :
      debug : 'debug'
      raw : 'compiled'
    steps :
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1

  release.raw :
    criterion :
      debug : 'release'
      raw : 1
    steps :
      - reflect.proto.*=1

  release.compiled :
    criterion :
      debug : 'release'
      raw : 'compiled'
    steps :
      - transpile.proto.no.tests*=1
      - transpile.proto.only.tests*=1
