
submodule :

path :

  proto : './proto'
  temp : 'out'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
    criterion :
      debug : 1
      compiled : 0
  out.debug.compiled :
    path : './out/debug.compiled'
    criterion :
      debug : 1
      compiled : 1
  out.release.raw :
    path : './out/release.raw'
    criterion :
      debug : 0
      compiled : 0
  out.release :
    path : './out/release'
    criterion :
      debug : 0
      compiled : 1

reflector :

  reflect.proto :
    inherit : predefined.*
    criterion :
      debug : [ 0,1 ]
      compiled : 0
    filePath :
      path::proto : path::out.*=1

  concat.proto.no.tests :
    inherit : predefined.*
    criterion :
      tests : 'no.tests'
      compiled : 1
      debug : [ 0,1 ]
    filePath :
      '**.test*' : 0
      '**.test/**' : 0
      path::proto : path::out.*=1

  concat.proto.only.tests :
    inherit : predefined.*
    criterion :
      tests : 'only.tests'
      debug : [ 0,1 ]
      compiled : 1
    filePath :
      '**.test*' : 1
      path::proto : path::out.*=1

step :

  reflect.proto :
    inherit : predefined.reflect
    reflector : reflector::reflect.proto.*=1
    criterion :
      debug : [ 0,1 ]
      raw : [ 0,1 ]

  concat.proto :
    inherit : predefined.concat.js
    reflector : reflector::concat.proto.*=1
    criterion :
      tests : [ 'no.tests', 'only.tests' ]
      debug : [ 0,1 ]
      raw : 0

build :

  debug.raw :
    criterion :
      default : 1
      debug : 1
      raw : 1
    steps :
      - step::reflect.proto.*=1

  debug.compiled :
    criterion :
      debug : 1
      raw : 0
    steps :
      # - step::concat.proto.no.tests*=1
      - step::concat.proto.only.tests*=1

  release.raw :
    criterion :
      debug : 0
      raw : 1
    steps :
      - step::reflect.proto.*=1

  release.compiled :
    criterion :
      debug : 0
      raw : 0
    steps :
      - step::concat.proto.*=1
