
about :

  name : export-proto-having-submodules
  description : Module exports proto but has submodules
  version : 0.1.0
  enabled : 1
  interpreters :
  - node >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0

step  :

  export.proto :
    inherit : module.export
    export : '{path::proto}/**'
    tar : 0
    criterion :
      debug : 1
      proto : 1

build :

  proto.export :
    criterion :
      default : 1
      debug : 1
      proto : 1
      raw : 1
      export : 1
      tar : 0
    steps :
      - step::export.proto
