about :

  name : predefinedSteps
  description : "To use predefined submodule control steps"
  version : 0.0.1

submodule :
  
  Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#master
  PathFundamentals : git+https:///github.com/Wandalen/wPathFundamentals.git/out/wPathFundamentals#master

step :

  echo :
    shell : echo "Done"
    currentPath : '.'
build :

  download :
    steps :
      - submodules.download

  update :
    steps :
      - submodules.update

  clean :
    steps :
      - submodules.clean
          
  clean.download :
    steps :
      - submodules.clean
      - submodules.reload
      - submodules.download
      - echo