
path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug : './out/debug'

reflector :

  reflect.proto :
    filePath :
      path::proto : path::out.debug

step :

  reflect.proto :
    inherit : predefined.reflect
    reflector :
      reflector::reflect.proto

build :

  debug :
    steps :
      - step::reflect.proto
