
path :

  # source : git:///git@bitbucket.org:stoneridgetechnology/encore.common.git#21f783b2040103235748a3ccb64eabbf34ef506f
  source : git+https:///github.com/Wandalen/wPathFundamentals.git
  pathFundamentals : 'wPathFundamentals'

reflector :

  download1 :
    src :
      prefixPath : path::source
    dst :
      basePath : .
      prefixPath : path::pathFundamentals

  download2 :
    src :
      prefixPath : path::source
    filePath :
      path::source : path::pathFundamentals

step :

  download1 :
    inherit : predefined.reflect
    reflector :
      reflector::download1

  download2 :
    inherit : predefined.reflect
    reflector :
      reflector::download2

build :

  download1 :
    criterion :
      default : 1
      debug : 1
    steps :
      - step::download1

  download2 :
    criterion :
      default : 1
      debug : 1
    steps :
      - step::download2