
about :

  name : "export-with-reflector"
  description : "Module for testing"
  version : "0.0.1"
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - wTools

step :

  export.proto :
    inherit : predefined.export
    export : reflector::proto.but.include
    tar : 0

build :

  proto.export :
    criterion :
      default : 1
      export : 1
    steps :
      - step::export.proto
