
about :

  name : multi-config ex
  description : "Multi-config module - export"
  version : 0.0.0

path :
  out : '.'
  fileToExport : './fileToExport'

step  :
  export.single :
      inherit : export
      tar : 0
      export : path::fileToExport

build :
  export :
      criterion :
          default : 1
          export : 1
      steps :
          - export.single
