about :

  name : Proto
  version : 0.1.0

path :

  in : .
  out : out
  remote : 'git+hd://../_repo/ModuleForTesting12'
  # remote : 'git+https:///github.com/Wandalen/wProto.git'
  # git:///git@bitbucket.org:group/repo.git/out/Repo#master
  local : '.module/ModuleForTesting12'
  export : '{path::local}/proto/**'
  temp : out

reflector :

  download :
    src : path::remote
    dst : path::local

step :

  export.common :
    export : path::export
    tar : 0

build :

  export :
    criterion :
      default : 1
      export : 1
    steps :
      - step::download
      - step::export.common
