about :

  name : setVerbosity
  description : "To use .set command"
  version : 0.0.1

submodule :
  PathFundamentals : git+https:///github.com/Wandalen/wPathFundamentals.git/out/wPathFundamentals#master

path :

  out : 'out'

  submodule.pathfundamental : '.module/PathFundamentals'

step  :

  export.submodule :
    export : path::submodule.*

build :

  submodules.download :
    criterion :
      default : 1
    steps :
      - submodules.download

  submodules.export :
    criterion :
      default : 1
      export : 1
    steps :
      - export.*
