about :
  name : 'compileCpp'
  description : 'To use willbe as make'
  version : 0.0.1

path :

  in : '.'
  file : 'file'

reflector :
  
  compile :
    filePath :
      '*.c' : 1
      path::file : 1
    src :
      prefixPath : 'file'
    dst :
      filePath : path::file

  build :
    filePath :
      '*.o' : 1
      '*.c' : 0
      path::file : 1
    src :
      prefixPath : 'file'
    dst :
      filePath : path::file
    shell : gcc -o {f::this/dst}/hello {f::this/src}

step :

  compile :
    shell : gcc -c {f::this/src}
    currentPath : path::file
    forEachDst : compile
    upToDate : preserve
  
  clean.temp :
    inherit: shell.run
    shell : rm -Rf *.o
    currentPath : path::file

build :

  compile :
    criterion :
      default : 1
    steps :
      - step::compile

  make.hello :
    steps :
      - step::build
  
  all :
    steps :
      - build::compile
      - build::make.hello
      - clean.temp
