
submodule :

  Bitmask : git+https:///github.com/Wandalen/wBitmask.git/out/wBitmask!master
  RegexpObject : git+https:///github.com/Wandalen/wRegexpObject.git/out/wRegexpObject!master
  ModuleForTesting1a : git+https:///github.com/Wandalen/wModuleForTesting1a.git/out/wModuleForTesting1a!master
  ModuleForTesting1a256 : git+https:///github.com/Wandalen/wModuleForTesting1a256.git/out/wModuleForTesting1a256!master
  ChangeTransactor : git+https:///github.com/Wandalen/wChangeTransactor.git/out/wChangeTransactor!master
  Vocabulary : git+https:///github.com/Wandalen/wVocabulary.git/out/wVocabulary!master
  CommandsAggregator : git+https:///github.com/Wandalen/wCommandsAggregator.git/out/wCommandsAggregator!master
  CommandsConfig : git+https:///github.com/Wandalen/wCommandsConfig.git/out/wCommandsConfig!master
  Files : git+https:///github.com/Wandalen/wFiles.git/out/wFiles!master
  FilesArchive : git+https:///github.com/Wandalen/wFilesArchive.git/out/wFilesArchive!master
  FilesEncoders : git+https:///github.com/Wandalen/wFilesEncoders.git/out/wFilesEncoders!master
  Verbal : git+https:///github.com/Wandalen/wVerbal.git/out/wVerbal!master
  StateStorage : git+https:///github.com/Wandalen/wStateStorage.git/out/wStateStorage!master
  StateSession : git+https:///github.com/Wandalen/wStateSession.git/out/wStateSession!master
  PathTranslator : git+https:///github.com/Wandalen/wPathTranslator.git/out/wPathTranslator!master
  FileExecutor : git+https:///github.com/Wandalen/wFileExecutor.git/out/wFileExecutor!master
  TranspilationStrategy : git+https:///github.com/Wandalen/wTranspile.git/out/wTranspile!master
  NameMapper : git+https:///github.com/Wandalen/wNameMapper.git/out/wNameMapper!master
  TemplateTreeResolver : git+https:///github.com/Wandalen/wTemplateTreeResolver.git/out/wTemplateTreeResolver!master
  TemplateTreeEnvironment : git+https:///github.com/Wandalen/wTemplateTreeEnvironment.git/out/wTemplateTreeEnvironment!master
  TemplateFileWriter : git+https:///github.com/Wandalen/wTemplateFileWriter.git/out/wTemplateFileWriter!master
  Graph : git+https:///github.com/Wandalen/wGraphBase.git/out/wGraphBase!master
  Communicator : git+https:///github.com/Wandalen/wCommunicator.git/out/wCommunicator!master
  Starter : git+https:///github.com/Wandalen/wStarter.git/out/wStarter!master

  # Testing : git+https:///github.com/Wandalen/wTesting.git/out/wTesting!master

path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
    criterion :
      debug : 1
  out.release :
    path : './out/release'
    criterion :
      debug : 0

reflector :

  reflect.proto :
    inherit : predefined.*
    criterion :
      debug : [ 0,1 ]
    filePath :
      path::proto : path::out.*=1

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst :
      basePath : .
      prefixPath : "{path::out.*=1}"
    criterion :
      debug : 1
