about :
  name : test
  description : "To test commands of willbe-package"
  version : 0.0.1

submodule :

  Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#master
  PathBasic : git+https:///github.com/Wandalen/wPathBasic.git/out/wPathBasic#master

path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug : 'out/debug'

reflector :

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exportedFiles*=1
    dst :
      basePath : .
      prefixPath : path::out.debug
    criterion :
      debug : 1

step :

  reflect.submodules :
    inherit : files.reflect
    reflector :
      reflector::reflect.submodules*=1

  delete.out.debug :
    inherit : files.delete
    filePath : path::out.debug

build :

  debug :
    criterion :
      default : 1
    steps :
      - submodules.download
      - delete.out.debug
      - reflect.submodules
