about :

  name : inheritability
  description : "To use resources inheritability"
  version : 0.0.1

path :

  out : 'out'

submodule :

   One : ./one/one.will.yml
   Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#master

reflector :

  inherit.remote:
    inherit : submodule::T*/exported::*=1/reflector::exportedFiles*=1
    dst:
      filePath: path::out
    criterion:
      debug: [ 0,1 ]

step :

  copy.all :
    inherit : predefined.reflect
    reflector : reflector::reflect.*
    criterion:
      debug: [ 0,1 ]

  reflect.copy :
    inherit : step::copy*
    reflector : reflector::inherit.*=1
    criterion:
      debug: 1

build :

  inherit.local :
    inherit: submodule::One/build::c*=1
    criterion :
      default : 1
      debug : 1