path :

  out : 'out'
  fileToExport : './node_modules/*'

step  :

  export.dependencies :
    inherit : module.export
    export : path::fileToExport
    tar : 0

build :

  export :
    criterion :
      default : 1
      export : 1
    steps :
      - export.dependencies