
submodule :

  module1 :
    path : hd://.
    enabled : 0 # submodule
    criterion :
      development : 1
  wTools :
    path : npm:///wTools
    enabled : 0 # submodule
    criterion :
      development : 1
  wTesting :
    path : npm:///wTesting
    enabled : 0 # submodule
    criterion :
      development : 1

path :

  in : '.'
  out : 'out'
  temp :
    - 'path::out'
    - 'package-lock.json'
    - 'package.json'
    - 'node_modules'
  proto : './proto'
  export : '{path::proto}/**'
  doc : './doc'
