
submodule :

  Tools : git+https:///github.com/Wandalen/wModuleForTesting1.git/@master
  ModuleForTesting2 : git+https:///github.com/Wandalen/wModuleForTesting2.git/@master
  PathTools : git+https:///github.com/Wandalen/wPathTools.git/@master
  # Proto : git+https:///github.com/Wandalen/wProto.git/@master
  # UriBasic : git+https:///github.com/Wandalen/wUriBasic.git/@master
  # Procedure : git+https:///github.com/Wandalen/wProcedure.git/@master
  # Color : git+https:///github.com/Wandalen/wColor.git/@master

path :

  proto : './proto'
  export : '{path::proto}/**'
  in : '.'
  out : 'out'
  out.proto : '{path::out}/proto'
  temp :
    - out
    - wExperiment/out

step :

  clean.out :
    inherit : files.delete
    filePath : path::out

reflector :

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst :
      prefixPath : 'path::out.proto'
    criterion :
      content: proto

build :

  build :
    criterion :
      default : 1
    steps :
      - clean.out
      - reflect.submodules
