
path :

  ModuleForTesting1.remote : https:///raw.githubusercontent.com/Wandalen/wModuleForTesting1/master/proto/dwtools/abase/l1/l1/ModuleForTesting1.s
  ModuleForTesting1.local : 'ModuleForTesting1.s'

reflector :

  download.1 :
    criterion :
      variant : 1
    filePath :
      path::ModuleForTesting1.remote : out/ModuleForTesting1.s

step :

  # download.1 :
  #   inherit : files.reflect
  #   criterion :
  #     variant : [ 1 ]
  #   reflector :
  #     reflector::download.*=1

build :

  download :
    criterion :
      variant : [ 1 ]
    steps :
      - step::download.*=1
