
about :

  name : 'NpmFromWillfile'
  description : 'To check the conversion'
  version : '0.0.0'
  enabled : 1
  interpreters :
  - nodejs >= 6.0.0
  - chrome >= 60.0.0
  - firefox >= 60.0.0
  keywords :
  - tools
  - export
  license : MIT
  author : 'Author <author@dot.com>'
  contributors :
  - 'Contributor1 <contributor1@dot.com>'
  - 'Contributor2 <contributor2@dot.com>'

path :

  repository : git+https:///github.com/author/NpmFromWillfile.git
  origins :
   - git+https:///github.com/author/NpmFromWillfile.git
   - npm:///npmfromwillfile
  bugtracker : https:///github.com/author/NpmFromWillfile/issues

step :

  proto.export :
    inherit : module.export
    export : '{path::proto}/**'
    tar : 0
    criterion :
      content : 'proto'

  doc.export :
    inherit : module.export
    export : path::doc
    tar : 0
    criterion :
      content : 'doc'

  npm.export :
    inherit : module.export
    export : out.npm
    tar : 0
    criterion :
      content : 'npm'

  npm.publish :
    shell : npm publish

build :

  proto.export :
    criterion :
      content : 'proto'
      export : 1
    steps :
      # - build::debug.raw
      - step::proto.export

  doc.export :
    criterion :
      content : 'doc'
      export : 1
    steps :
      # - build::debug.raw
      - step::doc.export

  npm.export :
    criterion :
      content : 'npm'
      export : 1
    steps :
      # - build::debug.raw
      # - step::npm.export
      - step::npm.publish

  export :

    criterion :
      default : 1
      export : 1
    steps :
      # - build::npm
      - build::proto.export
      # - build::doc.export
