submodule :

  submodule1 : submodule1
  submodule2 : submodule2

path :

  in : '.'
  out : './out'
  out.debug : './out/debug'

reflector :

  reflect.submodules :
    inherit :
      - submodule::submodule1/exported::*=1/reflector::exported.files*=1
      - submodule::submodule2/exported::*=1/reflector::exported.files*=1
    dst : path::out.debug

build :

  debug :
    criterion :
      default : 1
    steps :
      - step::reflect.submodules
