
path :

  PathBasic.remote : git+https:///github.com/Wandalen/wPathBasic.git
  PathBasic.local : 'PathBasic'

  Looker.remote : git+https:///github.com/Wandalen/wLooker.git
  Looker.local : 'Looker'

  Proto.remote : git+https:///github.com/Wandalen/wProto.git
  Proto.local : 'Proto'

reflector :

  download.1 :
    criterion :
      variant : 1
    filePath :
      path::PathBasic.remote : path::PathBasic.local

  download.2 :
    criterion :
      variant : 2
    src :
      filePath :
        path::PathBasic.remote : path::PathBasic.local

  download.3 :
    criterion :
      variant : 3
    dst :
      filePath :
        path::PathBasic.remote : path::PathBasic.local

  download.4 :
    criterion :
      variant : 4
    src :
      prefixPath : path::PathBasic.remote
      filePath :
        path::PathBasic.remote : path::PathBasic.local

  download.5 :
    criterion :
      variant : 5
    src :
      prefixPath : path::PathBasic.remote
    filePath :
      path::PathBasic.remote : path::PathBasic.local

  download.6 :
    criterion :
      variant : 6
    src :
      prefixPath : path::PathBasic.remote
    dst :
      basePath : .
      prefixPath : path::PathBasic.local

  download.7 :
    criterion :
      variant : 7
    filePath :
      path::PathBasic.remote : path::PathBasic.local
      path::Looker.remote : path::Looker.local
      path::Proto.remote : path::Proto.local

step :

  # download :
  #   inherit : files.reflect
  #   criterion :
  #     variant : [ 1,2,3,4,5,6,7 ]
  #   reflector :
  #     reflector::download.*=1

build :

  download :
    criterion :
      variant : [ 1,2,3,4,5,6,7 ]
    steps :
      - step::download.*=1
