
path :

  in : '.'
  out : 'out'
  A : 'proto/A'
  B : 'proto/B'
  
step : 
  clean.paths:
    inherit : files.delete
    filePath : 
      - path::A
      - path::B

build :

  def :
    criterion :
      default : 1
    steps :
      - clean.paths
