
path :
  int : '.'
  out : '.'
  fileToExport : './fileToExport'

step  :
  del :
    export : path::fileToExport

build :
  export :
    criterion :
      default : 1
      export : 1
    steps :
      - export.single
