
submodule :

  submodule : submodule

path :

  in : '.'
  out : './out'
  out.debug :
    path : './out/debug'

reflector :

  reflect.submodules :
    inherit : predefined.*
    filePath :
      submodule::*/exported::*=1/path::exportedDir*=1 : path::out.*=1
    src :
      basePath : '..'

step :

  reflect.submodules :
    inherit : predefined.reflect
    reflector :
      reflector::reflect.submodules*=1

build :

  debug :
    criterion :
      default : 1
    steps :
      - step::reflect.submodules
