
submodule :

  PathFundamentals : git+https:///github.com/Wandalen/wPathFundamentals.git/out/wPathFundamentals#master

path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
    criterion :
      debug : 1

reflector :

  reflect.submodules :
    inherit : predefined.*
    filePath :
      submodule::*/path::in*=1 : path::out.*=1
    src :
      basePath : '.module/PathFundamentals'
    criterion :
      debug : 1

step :

  reflect.submodules :
    inherit : predefined.reflect
    reflector :
      reflector::reflect.submodules*=1
    criterion :
      debug : 1

build :

  debug.raw :
    criterion :
      default : 1
      debug : 1
    steps :
      - submodules.download
      - reflect.submodules*=1

