about :

  name : willFileMinimizing
  description : "To minimize will-file by short write form of criterions"
  version : 0.0.1

path :

  in : '.'
  out : 'out'
  fileToDelete.debug :
    criterion :
      debug : 1
    path : './files/Debug*'

  fileToDelete.release :
    criterion :
      debug : 0
    path : './files/Release??'

step  :
  delete.files :
    inherit : predefined.delete
    filePath : path::fileToDelete.*=1
    criterion :
      debug : [ 0,1 ]

build :

  delete :
    criterion :
      debug : [ 0,1 ]
    steps :
      - delete.*=1
