about :

    name : predefinedSteps
    description : "To use predefined submodule control steps"
    version : 0.0.1

submodule :

    Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#master
    PathFundamentals : git+https:///github.com/Wandalen/wPathFundamentals.git/out/wPathFundamentals#master

step :

    echo :
        shell: echo "Done"

build :

    download :
        steps :
           - submodules.download

    upgrade :
        steps :
           - submodules.upgrade

    clean :
        steps :
           - submodules.clean

    echo:
        steps:
           - submodules.clean
           - submodules.download
           - echo
