submodule :
  Path : npm:///wpathbasic@alpha
  Uri : npm:///wuribasic#0.6.131

about :

  name : supermodule
  version : 0.1.0

path :

  in : .
  out : out
  
reflector :
 
  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst : 
      basePath : .
      prefixPath : 'path::out'

build :

  debug :
    criterion :
      default : 1
    steps :
      - step::reflect.submodules
