
submodule :

  Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#8db8861e59d31a041ea9d4356728f3d646786134
  PathBasic : git+https:///github.com/Wandalen/wPathBasic.git/out/wPathBasic.out.will#master
  UriBasic : git+https:///github.com/Wandalen/wUriBasic.git/out/wUriBasic#96a153b690d1dbc251881a70b14cc9e53d45918b

path :

  proto : './proto'
  in : '.'
  out : 'out'
  out.debug :
    path : './out/debug'
    criterion :
      debug : 1

reflector :

  reflect.proto :
    inherit : predefined.*
    criterion :
      debug : 1
    filePath :
      path::proto : path::out.*=1

  reflect.submodules :
    inherit : submodule::*/exported::*=1/reflector::exported.files*=1
    dst :
      basePath : .
      prefixPath : path::out.debug
    criterion :
      debug : 1

step :

  delete.out.debug :
    inherit : files.delete
    filePath : path::out.debug
    criterion :
      debug : 1

build :

  debug.raw :
    criterion :
      default : 1
    steps :
      - submodules.download
      - delete.out.debug
      - reflect.proto*=1
      - reflect.submodules*=1
