
submodule :

  A :
    path : ./module/A
    criterion :
      debug : 0
  B :
    path : ./module/B
    criterion :
      debug : 1

path :

  in : '.'
  out : 'out'
  out.debug : './out/debug'

reflector :

  reflect:
    inherit : submodule::*/exported::*=1/reflector::exportedFiles*=1
    dst :
      basePath : .
      prefixPath : path::out.debug
    criterion :
      debug : [ 0,1 ]

step :

  delete.out :
    inherit : predefined.delete
    filePath : path::out

build :

  A :
    criterion :
      debug : 0
    steps :
      - submodules.download
      - delete.out
      - reflect.*=1

  B :
    criterion :
      debug : 1
    steps :
      - submodules.download
      - delete.out
      - reflect.*=1
