about :
  name : test
  description : "To test commands of willbe-package"
  version : 0.0.1

submodule :

  Tools : git+https:///github.com/Wandalen/wTools.git/out/wTools#master
  PathFundamentals : git+https:///github.com/Wandalen/wPathBasic.git/out/wPathBasic#master

path :

  proto : 'proto'
  out.debug : 'out/debug'

step :

  delete.proto :
    inherit : files.delete
    filePath: path::proto

  delete.out.debug :
    inherit : files.delete
    filePath : path::out.debug

build :

  debug :
    criterion :
      default : 1
    steps :
      - submodules.download
      - delete.out.debug
      - delete.proto